version: '3.4'
services:
  fg-entra-stub-frontend:
    build: ./
    ports:
      - '3010:3010'
    env_file:
      - 'compose/aws.env'
    environment:
      NODE_ENV: development
      USE_SINGLE_INSTANCE_CACHE: true
    networks:
      - cdp-tenant

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
    name: cdp-tenant
